### ISSUE TITLE
buddypress-multilingual displays some fields names with escaping character / - as it is in database - thus it does not for options values, some filters seems to be inconsistent

### ISSUE THREAD

**Issue by eltb** [OnTheGoSystems/buddypress-multilingual#11]
Hello,

Some fields from Buddypress are displayed with slashes when they contain some ' or ".
Have found it for names and descriptions.

This seems to be a workaround : 

https://github.com/telabotanica/buddypress-multilingual/commit/45d87c9a080506198110cd7c1c5875716d885864

But I think there's something to do with WPML as some other fields are displayed without slashes.

Thanks,

Eric

Bad (slashes are displayed):

![capture-decran-de-2017-03-10-11-53-30](https://user-images.githubusercontent.com/29776142/28921980-9c567696-7858-11e7-8b56-6efa8f5a940c.png)

Good (slashes are not displayed) : 
![good_no_slash_patched](https://user-images.githubusercontent.com/29776142/28922134-3df95bee-7859-11e7-80f8-b4f2434f35e9.jpg)

**Comment by eltb** [comment]
This also happened for some other fields, and options.

See here :  https://github.com/telabotanica/buddypress-multilingual/pull/2

**Comment by eltb** [comment]
@eldk

**Comment by srdjan-jcc** [comment]
Thank you for reporting this and fix proposals.
We're considering to add filters that BuddyPress uses for field name and description:
'stripslashes' and 'wp_filter_kses'.
(see buddypress/bp-xprofile/bp-xprofile-filters.php)

We'll commit fixes here (new branch) soon:
https://github.com/OnTheGoSystems/buddypress-multilingual/tree/wpmlbridge-104

**Comment by eldk** [comment]
Hello @srdjan-jcc ,

>We're considering to add filters that BuddyPress uses for field name and description:
'stripslashes' and 'wp_filter_kses'.

Futher testing shows that some options may be affected too :  https://github.com/telabotanica/buddypress-multilingual/pull/2 .

So this may be applyed to options too.

Thanks,

Eric

@eltb, @spone, @matcho, @kstefanini

**Comment by srdjan-jcc** [comment]
@eldk @eltb After complete tests, we added `stripslashes` in needed places https://github.com/OnTheGoSystems/buddypress-multilingual/commit/aa410983d5342622ca18afb5eb4bb0741840456c
No need for `wp_kses` filters since BP already applied them.
Please you can use branch `wpmlbridge-104` to re-test.

For now `stripslashes` are added directly in needed places,
we plan code refactoring for near future.

There should be no backward compatibility issues for already translated/existing fields.
If you update fields, strings will be marked as 'Translation needs update', since we also fixed registering WPML strings.

**Comment by eldk** [comment]
Ok, thanks,
I will test it today and come back to report if it's solved.
Eric
@eltb, @Spone, @matcho, @kstefanini

**Comment by eldk** [comment]
Hello,

It's solved.

Thanks @srdjan-jcc

**Comment by srdjan-jcc** [comment]
Merged to develop branch https://github.com/OnTheGoSystems/buddypress-multilingual/pull/12
Soon we'll release with these fixes.
